ALTER TABLE "fines" ADD COLUMN IF NOT EXISTS "estatusAprobacion" VARCHAR(30) NOT NULL DEFAULT 'Pendiente';
ALTER TABLE "fines" ADD COLUMN IF NOT EXISTS "approvalStep" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "fines" ADD COLUMN IF NOT EXISTS "approvalTrail" JSONB;
