-- AlterEnum: ERP / compras / inventario / calidad
ALTER TYPE "NotificationType" ADD VALUE 'PURCHASE_REQUISITION_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'PURCHASE_REQUISITION_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'PURCHASE_REQUISITION_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'PURCHASE_ORDER_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'PURCHASE_ORDER_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'GOODS_RECEIPT_POSTED';
ALTER TYPE "NotificationType" ADD VALUE 'STOCK_MOVEMENT_POSTED';
ALTER TYPE "NotificationType" ADD VALUE 'QUALITY_NCR_CREATED';
