export const PERMISSIONS = {
  CONSOLE_ACCESS: 'console.access',
  CONSOLE_ADMIN: 'console.admin',
  PANEL_TIENDA: 'panel.tienda',
  PANEL_WEB: 'panel.web',
  PANEL_VENTAS: 'panel.ventas',
  ACTIVITIES_VIEW: 'activities.view',
  ACTIVITIES_MANAGE: 'activities.manage',
  ACTIVITIES_EXPORT: 'activities.export',
  ACTIVITIES_IMPORT: 'activities.import',
  EVIDENCES_VIEW: 'evidences.view',
  EVIDENCES_CREATE: 'evidences.create',
  EVIDENCES_REVIEW: 'evidences.review',
  EVIDENCES_EXPORT: 'evidences.export',
  EVIDENCES_IMPORT: 'evidences.import',
  VIATICS_VIEW: 'viatics.view',
  VIATICS_CREATE: 'viatics.create',
  VIATICS_MANAGE: 'viatics.manage',
  VIATICS_EXPORT: 'viatics.export',
  VIATICS_IMPORT: 'viatics.import',
  VEHICLES_VIEW: 'vehicles.view',
  VEHICLES_REQUEST: 'vehicles.request',
  VEHICLES_REVIEW: 'vehicles.review',
  VEHICLES_INVENTORY: 'vehicles.inventory',
  VEHICLES_EXPORT: 'vehicles.export',
  VEHICLES_IMPORT: 'vehicles.import',
  ATTENDANCE_VIEW: 'attendance.view',
  ATTENDANCE_MANAGE: 'attendance.manage',
  GPS_VIEW: 'gps.view',
  GPS_MANAGE: 'gps.manage',
  USERS_MANAGE: 'users.manage',
  USERS_REVIEW: 'users.review',
  ROLES_MANAGE: 'roles.manage',
  CONTABILIDAD_VIEW: 'contabilidad.view',
  CONTABILIDAD_MANAGE: 'contabilidad.manage',
  COTIZACIONES_ACCESS: 'cotizaciones.access',
  TOOLS_VIEW: 'tools.view',
  TOOLS_REQUEST: 'tools.request',
  TOOLS_MANAGE: 'tools.manage',
  TOOLS_INVENTORY: 'tools.inventory',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
