ALTER TYPE "NotificationType" ADD VALUE 'PRODUCTION_ORDER_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'PRODUCTION_ORDER_STATUS_CHANGED';
ALTER TYPE "NotificationType" ADD VALUE 'PRODUCTION_LOG_RECORDED';
ALTER TYPE "NotificationType" ADD VALUE 'JOURNAL_ENTRY_POSTED';
ALTER TYPE "NotificationType" ADD VALUE 'INVOICE_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'PAYMENT_REGISTERED';
ALTER TYPE "NotificationType" ADD VALUE 'MAINTENANCE_WORK_ORDER_CREATED';
