export {
  HikvisionIsapiClient,
  IsapiApiError,
  IsapiAuthRejectedError,
  IsapiNotConfiguredError,
  type IsapiClientOpts,
} from './isapi.client';

export {
  controlDoor,
  setChannelAudio,
  setHttpNotificationHost,
  clearHttpNotificationHost,
  readHttpNotificationHosts,
  enableMotionDetection,
  enableFieldDetection,
  enableHumanFieldDetection,
  enableLineDetection,
  enableFaceDetect,
  ensureSubstreamH264,
  enableMaxSmartDetection,
  ensureSmartEventTriggersCenter,
  enableNvrParkingVehicleDetection,
  disableFieldDetection,
  type MaxSmartDetectionReport,
  ptzMove,
  ptzStop,
  ptzGoToPreset,
  ptzPresets,
  type PtzPreset,
  describeDevice,
  discoverDevice,
  identifyDevice,
  listProxyChannels,
  listVideoChannels,
  supportsAccessControl,
  supportsAnpr,
  supportsPtz,
  type IsapiDeviceIdentity,
  type IsapiDeviceKind,
  type IsapiDiscoveredDevice,
  type IsapiProxyChannel,
  type IsapiVideoChannel,
} from './isapi.discovery';

export {
  captureFingerPrint,
  describeAcsEvent,
  deleteFaceData,
  deleteFingerPrint,
  deleteUserInfo,
  downloadFingerPrint,
  listAcsEvents,
  listAllUserInfo,
  mapIsapiUserToPersonDto,
  mapMirrorPersonToDto,
  modifyUserInfo,
  recordUserInfo,
  searchAcsEvents,
  searchUserInfo,
  uploadFaceData,
  uploadFingerPrint,
  searchFaceInfo,
  probeAcsIdentityCaps,
  type AcsEventPage,
  type CapturedFingerPrint,
  type DeviceOpResult,
  type IntegraPersonDto,
  type IsapiAcsEvent,
  type IsapiUserInfo,
  type UserInfoPage,
  type UserInfoWrite,
} from './isapi-acs';

export { probeRtsp, type RtspProbeResult } from './rtsp-probe';

export {
  ACCESS_SCHEDULE_MODEL_ES,
  INDEFINITE_VALID,
  WEEKDAYS,
  assignUserAccess,
  buildAfterHoursWeekPlan,
  buildAlwaysOnWeekPlan,
  buildOfficeHoursWeekPlan,
  buildWeekendWeekPlan,
  buildWeekPlanCfg,
  classifyValid,
  ensurePresetTemplate,
  getPlanTemplate,
  getWeekPlan,
  isHhMmSs,
  listPlanTemplates,
  listWeekPlanSummaries,
  parseRightPlan,
  putPlanTemplate,
  putWeekPlan,
  validFromMode,
  type AccessPresetKey,
  type PlanTemplate,
  type RightPlanEntry,
  type TimeSegment,
  type ValidMode,
  type WeekPlanCfg,
  type WeekPlanSlot,
  type Weekday,
} from './isapi-schedules';

export { asList, parseXml, pick, type XmlValue } from './xml';
