export {
  HikvisionIsapiClient,
  IsapiApiError,
  IsapiAuthRejectedError,
  IsapiNotConfiguredError,
  type IsapiClientOpts,
} from './isapi.client';

export {
  controlDoor,
  setChannelAudio,
  setHttpNotificationHost,
  clearHttpNotificationHost,
  enableHumanFieldDetection,
  disableFieldDetection,
  ptzMove,
  ptzStop,
  ptzGoToPreset,
  ptzPresets,
  type PtzPreset,
  describeDevice,
  discoverDevice,
  identifyDevice,
  listProxyChannels,
  listVideoChannels,
  supportsAccessControl,
  supportsAnpr,
  supportsPtz,
  type IsapiDeviceIdentity,
  type IsapiDeviceKind,
  type IsapiDiscoveredDevice,
  type IsapiProxyChannel,
  type IsapiVideoChannel,
} from './isapi.discovery';

export {
  captureFingerPrint,
  describeAcsEvent,
  deleteFaceData,
  deleteFingerPrint,
  deleteUserInfo,
  downloadFingerPrint,
  listAcsEvents,
  listAllUserInfo,
  mapIsapiUserToPersonDto,
  mapMirrorPersonToDto,
  modifyUserInfo,
  recordUserInfo,
  searchAcsEvents,
  searchUserInfo,
  uploadFaceData,
  uploadFingerPrint,
  type AcsEventPage,
  type CapturedFingerPrint,
  type DeviceOpResult,
  type IntegraPersonDto,
  type IsapiAcsEvent,
  type IsapiUserInfo,
  type UserInfoPage,
  type UserInfoWrite,
} from './isapi-acs';

export { probeRtsp, type RtspProbeResult } from './rtsp-probe';

export { asList, parseXml, pick, type XmlValue } from './xml';
