export {
  HikvisionIsapiClient,
  IsapiApiError,
  IsapiAuthRejectedError,
  IsapiNotConfiguredError,
  type IsapiClientOpts,
} from './isapi.client';

export {
  controlDoor,
  setChannelAudio,
  setHttpNotificationHost,
  clearHttpNotificationHost,
  readHttpNotificationHosts,
  enableMotionDetection,
  enableFieldDetection,
  enableHumanFieldDetection,
  enableLineDetection,
  enableFaceDetect,
  ensureSubstreamH264,
  enableMaxSmartDetection,
  ensureSmartEventTriggersCenter,
  enableNvrParkingVehicleDetection,
  disableFieldDetection,
  probeSmartCapabilities,
  type MaxSmartDetectionReport,
  ptzMove,
  ptzStop,
  ptzGoToPreset,
  ptzPresets,
  type PtzPreset,
  describeDevice,
  discoverDevice,
  identifyDevice,
  listProxyChannels,
  listVideoChannels,
  supportsAccessControl,
  supportsAnpr,
  supportsPtz,
  type IsapiDeviceIdentity,
  type IsapiDeviceKind,
  type IsapiDiscoveredDevice,
  type IsapiProxyChannel,
  type IsapiVideoChannel,
} from './isapi.discovery';

export {
  captureFingerPrint,
  describeAcsEvent,
  deleteFaceData,
  deleteFingerPrint,
  deleteUserInfo,
  downloadFingerPrint,
  listAcsEvents,
  listAllCardInfo,
  listAllUserInfo,
  mapIsapiUserToPersonDto,
  mapMirrorPersonToDto,
  modifyUserInfo,
  recordUserInfo,
  searchAcsEvents,
  searchCardInfo,
  searchUserInfo,
  uploadFaceData,
  uploadFingerPrint,
  searchFaceInfo,
  probeAcsIdentityCaps,
  type AcsEventPage,
  type CardInfoPage,
  type CapturedFingerPrint,
  type DeviceOpResult,
  type IntegraPersonDto,
  type IsapiAcsEvent,
  type IsapiCardInfo,
  type IsapiUserInfo,
  type MirrorPersonRow,
  type UserInfoPage,
  type UserInfoWrite,
} from './isapi-acs';

export {
  ALARM_CONFIDENCES,
  APPENDIX_B_EVENT_TYPES,
  CAMERA_HEALTH_EVENT_TYPES,
  DEFAULT_SENSITIVITY,
  DETECTION_TARGETS,
  MAX_DETECTION_REGIONS,
  SMART_EVENT_TYPES,
  clampSensitivity,
  fullFrameRegion,
  isAlarmConfidence,
  isAppendixBEventType,
  isCameraHealthEventType,
  isDetectionTarget,
  parseSmartCapabilities,
  patchFieldDetectionXml,
  patchLineDetectionXml,
  readNormalizedGrid,
  regionToCoordinatesList,
  replaceTagIfPresent,
  resolveTriggerEventTypes,
  resolveTuning,
  sanitizeRegions,
  supportedEventTypesFrom,
  upsertTag,
  type AlarmConfidence,
  type AppendixBEventType,
  type CameraHealthEventType,
  type DetectionTarget,
  type DetectionTuning,
  type FieldDetectionPatch,
  type LineDetectionPatch,
  type NormalizedPoint,
  type NormalizedRegion,
  type ResolvedDetectionTuning,
  type SmartCapabilities,
  type SmartEventType,
} from './isapi.detection';

export { probeRtsp, type RtspProbeResult } from './rtsp-probe';

export {
  ACCESS_SCHEDULE_MODEL_ES,
  INDEFINITE_VALID,
  WEEKDAYS,
  assignUserAccess,
  buildAfterHoursWeekPlan,
  buildAlwaysOnWeekPlan,
  buildOfficeHoursWeekPlan,
  buildWeekendWeekPlan,
  buildWeekPlanCfg,
  classifyValid,
  ensurePresetTemplate,
  getPlanTemplate,
  getWeekPlan,
  isHhMmSs,
  listPlanTemplates,
  listWeekPlanSummaries,
  parseRightPlan,
  putPlanTemplate,
  putWeekPlan,
  validFromMode,
  PRESET_TEMPLATE_SLOTS,
  presetSlot,
  type AccessPresetKey,
  type PlanTemplate,
  type RightPlanEntry,
  type TimeSegment,
  type ValidMode,
  type WeekPlanCfg,
  type WeekPlanSlot,
  type Weekday,
} from './isapi-schedules';

export { asList, parseXml, pick, type XmlValue } from './xml';
